# Generated by Django 5.0.1 on 2024-01-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_coments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='coments',
            name='reply',
        ),
    ]
