# Generated by Django 5.0.1 on 2024-01-21 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_alter_post_options_remove_coments_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
