# Generated by Django 5.0.1 on 2024-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('daraja', models.CharField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
