# Generated by Django 5.0.1 on 2024-02-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abouts',
        ),
    ]
